// config/shortcuts.ts
export const keyboardShortcuts = [
  { keys: ["⌘", "n"], action: "newEmail" },
  { keys: ["⌘", "Enter"], action: "sendEmail" },
  { keys: ["⌘", "r"], action: "reply" },
  { keys: ["⌘", "Shift", "r"], action: "replyAll" },
  { keys: ["⌘", "f"], action: "forward" },
  { keys: ["⌘", "Shift", "d"], action: "drafts" },
  { keys: ["⌘", "Shift", "i"], action: "inbox" },
  { keys: ["⌘", "Shift", "s"], action: "sentMail" },
  { keys: ["⌘", "Backspace"], action: "delete" },
  { keys: ["⌘", "/"], action: "search" },
  { keys: ["⌘", "Shift", "u"], action: "markAsUnread" },
  { keys: ["⌘", "Shift", "m"], action: "muteThread" },
  { keys: ["⌘", "Shift", "p"], action: "printEmail" },
  { keys: ["⌘", "Shift", "h"], action: "archiveEmail" },
  { keys: ["⌘", "Shift", "j"], action: "markAsSpam" },
  { keys: ["⌘", "Shift", "e"], action: "moveToFolder" },
  { keys: ["⌘", "Shift", "t"], action: "undoLastAction" },
  { keys: ["⌘", "Shift", "v"], action: "viewEmailDetails" },
  { keys: ["⌘", "Shift", "g"], action: "goToDrafts" },
  { keys: ["⌘", "Shift", "x"], action: "expandEmailView" },
  { keys: ["⌘", "?"], action: "helpWithShortcuts" },
];
