// config/shortcuts.ts
export const keyboardShortcuts = [
  { keys: ["c"], action: "newEmail" },                            
  { keys: ["⌘", "Enter"], action: "sendEmail" },
  { keys: ["r"], action: "reply" },                               
  { keys: ["a"], action: "replyAll" },                            
  { keys: ["f"], action: "forward" },                             
  { keys: ["g", "d"], action: "drafts" },                          
  { keys: ["g", "i"], action: "inbox" },                           
  { keys: ["g", "t"], action: "sentMail" },                        
  { keys: ["#"], action: "delete" },                               
  { keys: ["/"], action: "search" },                               
  { keys: ["u"], action: "markAsUnread" },                         
  { keys: ["m"], action: "muteThread" },                           
  { keys: ["⌘", "p"], action: "printEmail" },                      
  { keys: ["e"], action: "archiveEmail" },                         
  { keys: ["!"], action: "markAsSpam" },                           
  { keys: ["v"], action: "moveToFolder" },                         
  { keys: ["z"], action: "undoLastAction" },                       
  { keys: ["i"], action: "viewEmailDetails" },                     
  { keys: ["g", "d"], action: "goToDrafts" },                     
  { keys: ["o"], action: "expandEmailView" },                     
  { keys: ["?"], action: "helpWithShortcuts" },                   
];
